"""Add remedy_steps column to alerts

Revision ID: 18ed60ffa698
Revises: a066ad20885b
Create Date: 2025-08-23 21:43:00.938943

"""
from alembic import op
from sqlalchemy import Text
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18ed60ffa698'
down_revision = 'a066ad20885b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedy_steps', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('remedy_steps')

    # ### end Alembic commands ###
