"""Add deprecated/last_updated to MITRE tables

Revision ID: 19d6113ca6f6
Revises: a982735dddf5
Create Date: 2025-08-16 11:54:28.370006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d6113ca6f6'
down_revision = 'a982735dddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitre_tactics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deprecated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitre_tactics', schema=None) as batch_op:
        batch_op.drop_column('deprecated')

    # ### end Alembic commands ###
