"""Add md5_hash to LogEntry

Revision ID: 1cdd8697325a
Revises: 733ad7321faf
Create Date: 2025-08-03 10:06:45.352289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdd8697325a'
down_revision = '733ad7321faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('md5_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_md5_hash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_md5_hash'), ['md5_hash'], unique=1)
        batch_op.alter_column('md5_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
