"""Add signature_hex to FimBaseline

Revision ID: 1d0ce04d9057
Revises: b0c687eadb2d
Create Date: 2025-08-30 16:59:55.966669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0ce04d9057'
down_revision = 'b0c687eadb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_hex', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.drop_column('signature_hex')

    # ### end Alembic commands ###
