"""Add hash and IOC fields to Alert model

Revision ID: 2f87b350386b
Revises: 53c5a86f817e
Create Date: 2025-08-03 12:07:04.156951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f87b350386b'
down_revision = '53c5a86f817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('md5_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sha256_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ioc_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ioc_value', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('ioc_value')
        batch_op.drop_column('ioc_type')
        batch_op.drop_column('sha256_hash')
        batch_op.drop_column('md5_hash')

    # ### end Alembic commands ###
