"""Add matched_log_id to Alert

Revision ID: 3c971d424b7d
Revises: 4b16c52bb7b6
Create Date: 2025-08-01 20:17:21.107829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c971d424b7d'
down_revision = '4b16c52bb7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_log_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_alerts_matched_log_id_logs',  # Constraint name (must be unique)
            'logs',                           # Referenced table
            ['matched_log_id'],              # Local column
            ['id']                           # Referenced column
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('matched_log_id')

    # ### end Alembic commands ###
