"""Add users and alerts tables

Revision ID: 4b16c52bb7b6
Revises: f1e5c45553f9
Create Date: 2025-07-31 16:35:53.496240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '4b16c52bb7b6'
down_revision = 'f1e5c45553f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('min_severity', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('emerging_threats', sa.Text(), nullable=True),
    sa.Column('mitre_tactics', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_index_rule_id'), ['rule_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rule_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('technique_id', sa.String(length=50), nullable=True),
    sa.Column('technique_name', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('detected_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('user')
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_index_rule_id'))

    op.drop_table('rule_index')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
