"""Add enrichment fields to Alert

Revision ID: 53c5a86f817e
Revises: 1cdd8697325a
Create Date: 2025-08-03 11:37:44.388742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c5a86f817e'
down_revision = '1cdd8697325a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrichment_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enrichment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('enrichment_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('enrichment_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('enrichment_timestamp')
        batch_op.drop_column('enrichment_source')
        batch_op.drop_column('enrichment_status')
        batch_op.drop_column('enrichment_data')

    # ### end Alembic commands ###
