"""Add new columns to User table

Revision ID: 733ad7321faf
Revises: 93651d7139c4
Create Date: 2025-08-02 12:32:24.296539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733ad7321faf'
down_revision = '93651d7139c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('family_contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('personal_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('office_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('academic_certificate_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('international_certificate_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('is_rejected')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('international_certificate_path')
        batch_op.drop_column('academic_certificate_path')
        batch_op.drop_column('office_email')
        batch_op.drop_column('personal_email')
        batch_op.drop_column('family_contact_number')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
