"""Add severity, description, log_type, mitre fields to RuleIndex

Revision ID: 769a1081231f
Revises: 3c971d424b7d
Create Date: 2025-08-02 08:51:36.554613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769a1081231f'
down_revision = '3c971d424b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('log_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mitre_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mitre_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.drop_column('mitre_link')
        batch_op.drop_column('mitre_id')
        batch_op.drop_column('log_type')
        batch_op.drop_column('severity')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
