"""Add ai_suggestions JSON column to Alert

Revision ID: 790c6711b26b
Revises: fafa178815d9
Create Date: 2025-08-12 11:42:22.485603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '790c6711b26b'
down_revision = 'fafa178815d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggestions', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('ai_suggestions')

    # ### end Alembic commands ###
