"""Add FIM baseline and events tables

Revision ID: 802c39b2793d
Revises: e7851c4aaa93
Create Date: 2025-08-30 16:12:18.953590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802c39b2793d'
down_revision = 'e7851c4aaa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fim_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hash_sha256', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('signature_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fim_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('old_hash', sa.String(), nullable=True),
    sa.Column('new_hash', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('signature_status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('intel_status', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['fim_baseline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fim_events')
    op.drop_table('fim_baseline')
    # ### end Alembic commands ###
