"""Add cvss_score column to Alert table

Revision ID: 838d9f0b5ea4
Revises: 19d6113ca6f6
Create Date: 2025-08-16 17:15:21.154772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838d9f0b5ea4'
down_revision = '19d6113ca6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tactic_mapping')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('cvss_score')

    op.create_table('tactic_mapping',
    sa.Column('tactic_code', sa.TEXT(), nullable=True),
    sa.Column('tactic_uuid', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('tactic_code')
    )
    # ### end Alembic commands ###
