"""Add AlertStepWork, AlertEvidence, AlertHistory with NIST steps

Revision ID: 8e65683c0943
Revises: 6108e68c9752
Create Date: 2025-08-24 11:07:50.788557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e65683c0943'
down_revision = '6108e68c9752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['alert_step_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_step_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nist_phase', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sub_step', sa.String(length=100), nullable=False))
        batch_op.drop_column('step_name')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_step_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('step_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('sub_step')
        batch_op.drop_column('nist_phase')

    op.drop_table('alert_evidence')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
