"""Add decoder_name and rule_group to LogEntry

Revision ID: 98c7532078e2
Revises: 003a45a59fe6
Create Date: 2025-09-25 19:08:55.995185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c7532078e2'
down_revision = '003a45a59fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decoder_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rule_group', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_logs_decoder_name'), ['decoder_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_decoder_name'))
        batch_op.drop_column('rule_group')
        batch_op.drop_column('decoder_name')

    # ### end Alembic commands ###
