"""Add assigned_to_id column to Alert

Revision ID: 9fa8bf9ce08a
Revises: ab70ba4f0496
Create Date: 2025-08-21 22:21:59.916073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa8bf9ce08a'
down_revision = 'ab70ba4f0496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_alerts_assigned_to_user', 'user', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    # ### end Alembic commands ###
