"""Add is_escalated column to Alert

Revision ID: a066ad20885b
Revises: e7faa1988624
Create Date: 2025-08-22 22:04:48.802799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a066ad20885b'
down_revision = 'e7faa1988624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_escalated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('is_escalated')

    # ### end Alembic commands ###
