"""Add MITRE ATT&CK tables

Revision ID: a982735dddf5
Revises: 790c6711b26b
Create Date: 2025-08-16 10:48:48.876935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a982735dddf5'
down_revision = '790c6711b26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.String(length=10), nullable=True),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=True),
    sa.Column('next_scheduled_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitre_tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('mitre_version', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tactic_id')
    )
    op.create_table('mitre_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tactic_id', sa.String(length=20), nullable=False),
    sa.Column('tactic_name', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('mitigations', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('mitre_version', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactics.tactic_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitre_techniques')
    op.drop_table('mitre_tactics')
    op.drop_table('mitre_metadata')
    # ### end Alembic commands ###
