"""Add TaskStep table for remediation steps

Revision ID: ab70ba4f0496
Revises: 838d9f0b5ea4
Create Date: 2025-08-20 22:27:13.251750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ab70ba4f0496'
down_revision = '838d9f0b5ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_file', sa.String(length=255), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.drop_table('_alembic_tmp_alerts')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('probability')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('behavior_score')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
        batch_op.drop_index(batch_op.f('idx_tasks_assigned_status'))
        batch_op.drop_index(batch_op.f('idx_tasks_type_priority'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tasks_type_priority'), ['type', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_assigned_status'), ['assigned_to', 'status'], unique=False)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('behavior_score', sa.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('probability', sa.FLOAT(), server_default=sa.text('(0.5)'), nullable=True))

    op.create_table('_alembic_tmp_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rule_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('rule_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.INTEGER(), nullable=True),
    sa.Column('tactic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('technique_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('technique_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('playbook_id', sa.INTEGER(), nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('detected_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('matched_log_id', sa.INTEGER(), nullable=True),
    sa.Column('enrichment_data', sqlite.JSON(), nullable=True),
    sa.Column('enrichment_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('enrichment_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('enrichment_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('md5_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sha256_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('ioc_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ioc_value', sa.TEXT(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=False),
    sa.Column('ai_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('cvss_score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['matched_log_id'], ['logs.id'], name=op.f('fk_alerts_matched_log_id_logs')),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_steps')
    # ### end Alembic commands ###
