"""Unified models into models.py

Revision ID: ac41fbfe58d1
Revises: 2f87b350386b
Create Date: 2025-08-05 08:25:16.441377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac41fbfe58d1'
down_revision = '2f87b350386b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('decoders')
    #op.drop_table('detection_rules')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('is_new')
        batch_op.drop_column('log_id')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('log_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('md5_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_logs_md5_hash'), ['md5_hash'])
        batch_op.drop_column('processed')
        batch_op.drop_column('agent_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('processed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_logs_md5_hash'))
        batch_op.alter_column('md5_hash',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('log_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_new', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.alter_column('severity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('detection_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rule_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tactic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decoders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
