"""Updated models with FIM event and related changes

Revision ID: b06c1d3508f7
Revises: 1d0ce04d9057
Create Date: 2025-08-30 19:28:02.672536

"""
from sqlalchemy import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b06c1d3508f7'
down_revision = '1d0ce04d9057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_metadata', postgresql.JSON(astext_type=Text()), nullable=True))

    with op.batch_alter_table('fim_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('additional_metadata', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.drop_column('signature_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('additional_metadata')
        batch_op.drop_column('status')

    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.drop_column('additional_metadata')

    # ### end Alembic commands ###
