"""Add hash_algo to FimBaseline

Revision ID: b0c687eadb2d
Revises: 802c39b2793d
Create Date: 2025-08-30 16:43:45.412980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c687eadb2d'
down_revision = '802c39b2793d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_algo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fim_baseline', schema=None) as batch_op:
        batch_op.drop_column('hash_algo')

    # ### end Alembic commands ###
