"""Add is_new column to alerts

Revision ID: c551415d3c7f
Revises: ac41fbfe58d1
Create Date: 2025-08-05 08:52:53.182762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c551415d3c7f'
down_revision = 'ac41fbfe58d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))
    op.execute('UPDATE alerts SET is_new = 0 WHERE is_new IS NULL')
    with op.batch_alter_table('alerts') as batch_op:
        # Step 3: Alter column to NOT NULL if needed (SQLite has limitations)
        batch_op.alter_column('is_new', nullable=False)
 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
