"""Add reviewer fields to AlertStepWork

Revision ID: ca0c03c849fd
Revises: d8d1e8fa5be8
Create Date: 2025-08-24 14:56:39.995338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0c03c849fd'
down_revision = 'd8d1e8fa5be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_step_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_alertstepwork_reviewed_by', 'user', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_step_work', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_status')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
