"""Add file_hash column to AlertEvidence

Revision ID: d8d1e8fa5be8
Revises: 8e65683c0943
Create Date: 2025-08-24 12:29:43.156028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d1e8fa5be8'
down_revision = '8e65683c0943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_evidence', schema=None) as batch_op:
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
