"""Initial migration

Revision ID: f1e5c45553f9
Revises: 
Create Date: 2025-07-31 16:24:52.770272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f1e5c45553f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decoders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('log_type', sa.String(length=64), nullable=True),
    sa.Column('raw_log', sa.JSON(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('min_severity', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('emerging_threats', sa.Text(), nullable=True),
    sa.Column('mitre_tactics', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_index_rule_id'), ['rule_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rule_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('technique_id', sa.String(length=50), nullable=True),
    sa.Column('technique_name', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('detected_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('user')
    with op.batch_alter_table('rule_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_index_rule_id'))

    op.drop_table('rule_index')
    op.drop_table('playbooks')
    op.drop_table('logs')
    op.drop_table('detection_rules')
    op.drop_table('decoders')
    op.drop_table('agent_heartbeat')
    # ### end Alembic commands ###
